<?php
echo '<!Doctype HTML>';
echo '<html>';
echo '<head>';
echo '<title> Website </title>';
echo '<link rel="stylesheet" type="text/css" href="style.css">';
echo '</head>';
echo '<body>';
echo '<header>';
echo '<a href="#" class="logo">About Me</a>';
echo '<ul>';
echo '<li><a href="#" class="active">Home</a></li>';
echo '<li><a href="#">About</a></li>';
echo '<li><a href="#">Work</a></li>';
echo '<li><a href="#">Contact</a></li>';
echo script_tag('js/index.js');
echo '</ul>';
echo '</header>';
echo '<section>';
// echo img('images/bgbg.png');
echo '<h2 id="text"> Personal Portfolio</h2>';
echo '<a href="#" id="btn">Portfolio</a>';
echo '<img src="front2.png" id="front2">';
echo '</section>';
echo '<div class="sec" id="sec">';
echo '<h2>Hello</h2>';
echo img('images/me.png');
echo '<br>';
echo '<br>';
echo '<br>';
echo '<p> Name : Althea Noelle Sarmiento <br>';
echo 'Nickname : Thea / Noelle <br>';
echo 'Age : 20 Years Old <br>';
echo 'Hobbies : Drawing / Writing <br>';
echo '<br>';
echo 'Senior Highschool : Pasay City National Science Highschool <br>';
echo 'Course : Bachelor of Science in Computer Science Specialization in Cybersecurity and Forensics <br>';
echo 'Scholarship : 50% <br>';
echo 'IT experience / Others : Robotics <br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '</p>';
echo '';
echo img('images/cat.jpeg');
echo link_tag('css/style.css');
echo '</body>';
echo '</html>';
echo '';
?>